name: FolderResourcePackLoader
main: kim.present.folderresourcepackloader.Main
version: "0.1.0"
api: [ "1.0.11" ]
author: Author
description: Load resource packs in folder format
depend: [ KotlinLib ]